In [2]:
import numpy as np
import random

a = [[5,1,7,9,3,6,2,4,8],
     [9,6,2,1,8,4,5,3,7],
     [3,8,4,5,7,2,6,1,9],
     [6,9,8,4,5,7,3,2,1],
     [4,2,1,3,6,9,8,7,5],
     [7,5,3,8,2,1,4,9,6],
     [8,3,9,7,4,5,1,6,2],
     [1,4,6,2,9,8,7,5,3],
     [2,7,5,6,1,3,9,8,4]]

c = np.array([[5,1,7,9,3,6,2,4,8],
              [9,6,2,1,8,4,5,3,7],
              [3,8,4,5,7,2,6,1,9],
              [6,9,8,4,5,7,3,2,1],
              [4,2,1,3,6,9,8,7,5],
              [7,5,3,8,2,1,4,9,6],
              [8,3,9,7,4,5,1,6,2],
              [1,4,6,2,9,8,7,5,3],
              [2,7,5,6,1,3,9,8,4]])

d = c


def more():
    
    print(":LEVELS:")
    print("1.Beginner")
    print("2.Easy")
    print("3.Medium")
    print("4.Hard")

    l = input("Level Number:")

    if(l == '1'):
        for i in range(23):
            r1 = random.randint(0,8)
            r2 = random.randint(0,8)
            c[r1][r2] = 0


    elif(l == '2'):
        for i in range(36):
            r1 = random.randint(0,8)
            r2 = random.randint(0,8)
            c[r1][r2] = 0


    elif(l == '3'):
        for i in range(45):
            r1 = random.randint(0,8)
            r2 = random.randint(0,8)
            c[r1][r2] = 0


    elif(l == '4'):
        for i in range(53):
            r1 = random.randint(0,8)
            r2 = random.randint(0,8)
            c[r1][r2] = 0

    print(c)
    
s='y'

while(input("do u a another question(y/n):")!='n'):
    more()
    

do u a another question(y/n)y
:LEVELS:
1.Beginner
2.Easy
3.Medium
4.Hard
Level Number:4
[[5 0 7 9 3 0 2 4 0]
 [0 0 0 1 8 4 5 0 7]
 [0 0 4 5 7 0 6 0 0]
 [0 9 0 0 5 7 0 2 1]
 [0 0 1 3 0 0 0 7 5]
 [0 5 0 8 0 0 0 9 0]
 [8 0 0 7 0 5 0 6 0]
 [1 0 6 2 9 0 0 5 3]
 [2 0 0 0 1 3 9 8 0]]
do u a another question(y/n)n


In [7]:
import numpy as np

qq = input("question")
qq = qq.split('  ')
for i in range(9):
    qq[i] = qq[i].split(' ')
    if i is 0:
        qq[i][0] = qq[i][0][2]
        qq[i][8] = qq[i][8][0]
    elif i is 8:
        qq[i][8] = qq[i][8][0]
        qq[i][0] = qq[i][0][1]
    else:
        qq[i][0] = qq[i][0][1]
        qq[i][8] = qq[i][8][0]
            
    for j in range(9):
        qq[i][j] = int(qq[i][j])
        
#print(np.matrix(qq))

question[[5 0 7 9 3 0 2 4 0]  [0 0 0 1 8 4 5 0 7]  [0 0 4 5 7 0 6 0 0]  [0 9 0 0 5 7 0 2 1]  [0 0 1 3 0 0 0 7 5]  [0 5 0 8 0 0 0 9 0]  [8 0 0 7 0 5 0 6 0]  [1 0 6 2 9 0 0 5 3]  [2 0 0 0 1 3 0 0 0]]


In [8]:
def satisfaction(i,j,n):
    global qq
    for m1 in range(9):
        if qq[i][m1] == n:
            return False
    for m1 in range(9):
        if qq[m1][j] == n:
            return False
    for m1 in range((i//3)*3,(i//3+1)*3):
        for m2 in range((j//3)*3,(j//3+1)*3):
            if qq[m1][m2] == n:
                return False
    return True

In [11]:
def solution():
    global qq
    for i in range(9):
        for j in range(9):
            if qq[i][j] == 0:
                for k in range(1,10):
                    if satisfaction(i,j,k):
                        qq[i][j] = k
                        solution()
                        qq[i][j] = 0
                return
    print(np.matrix(qq))
    #input("do u need another solution if possible?")

In [12]:
solution()

[[5 1 7 9 3 6 2 4 8]
 [9 6 2 1 8 4 5 3 7]
 [3 8 4 5 7 2 6 1 9]
 [6 9 8 4 5 7 3 2 1]
 [4 2 1 3 6 9 8 7 5]
 [7 5 3 8 2 1 4 9 6]
 [8 3 9 7 4 5 1 6 2]
 [1 4 6 2 9 8 7 5 3]
 [2 7 5 6 1 3 9 8 4]]
